issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
  exclude:
    - 'SA1019: strings.Title'

run:
  timeout: 5m
  skip-dirs:
    - plz-out
    - .idea
